Tienda/Tienda/Models/ErrorViewModel.cs
using System;

namespace Tienda.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tienda/Tienda/Models/Productos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace Tienda.Models
{
    public class Productos
    {
        [Key]
        [Display(Name = "N°")]
        public int Product_id { get; set; }

        [Required(ErrorMessage = "Ingresa el código del producto")]
        [Display(Name = "Código del Producto")]
        public string Product_code { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del producto")]
        [Display(Name = "Nombre del Producto")]
        public string Product_name { get; set; }

        [Required(ErrorMessage = "Ingresa la presentación del producto")]
        [Display(Name = "Descripción")]
        public string Product_desc { get; set; }

        [Required(ErrorMessage = "Ingresa el precio del producto")]
        [Display(Name = "Precio del producto")]
        public int Product_price { get; set; }
    }
}

Tienda/Tienda/Models/TiendaContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tienda.Models
{
    public class TiendaContext : DbContext
    {
        public TiendaContext(DbContextOptions<TiendaContext> options) : base(options)
        {
        }

        public DbSet<Productos> Productos { get; set; }

    }
}

Tienda/Tienda/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Tienda.Models;

namespace Tienda.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tienda/Tienda/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tienda.Models;

namespace Tienda.Controllers
{
    public class ProductosController : Controller
    {
        private readonly TiendaContext _context;

        public ProductosController(TiendaContext context)
        {
            _context = context;


        }


        [HttpGet]
        public async Task<IActionResult> Index(string searchp)
        {
            ViewData["GetEmployeeDetails"] = searchp;
            var buscaquery = from x in _context.Productos select x;

            if (!String.IsNullOrEmpty(searchp))
            {
                buscaquery = buscaquery.Where(x => x.Product_name.Contains(searchp) || x.Product_code.Contains(searchp));
            }

            return View(await buscaquery.AsNoTracking().ToListAsync());
        }



        public IActionResult Index()
        {
            var displaydata = _context.Productos.ToList();
            return View(displaydata);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult  Create(Productos nProduct)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nProduct);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nProduct);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _context.Productos.FindAsync(id);

            return View(getEmpDetail);


        }

        [HttpPost]
        public async Task<IActionResult> Editar(Productos actualCustomer)
        {
            if (ModelState.IsValid)
            {
                _context.Update(actualCustomer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(actualCustomer);

        }

        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _context.Productos.FindAsync(id);

            return View(getEmpDetail);


        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {
            var getEmpdetail = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(getEmpdetail);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Detalles(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getDetail = await _context.Productos.FindAsync(id);

            return View(getDetail);
        }

    }
}

Tienda/Tienda/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tienda/Tienda/Views/Productos/Create.cshtml
@model Tienda.Models.Productos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Productos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <!--<div class="form-group">
                <label asp-for="Product_id" class="control-label"></label>
                <input asp-for="Product_id" class="form-control" />
                <span asp-validation-for="Product_id" class="text-danger"></span>
            </div>-->
            <div class="form-group">
                <label asp-for="Product_code" class="control-label"></label>
                <input asp-for="Product_code" class="form-control" />
                <span asp-validation-for="Product_code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_name" class="control-label"></label>
                <input asp-for="Product_name" class="form-control" />
                <span asp-validation-for="Product_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_desc" class="control-label"></label>
                <input asp-for="Product_desc" class="form-control" />
                <span asp-validation-for="Product_desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_price" class="control-label"></label>
                <input asp-for="Product_price" class="form-control" />
                <span asp-validation-for="Product_price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tienda/Tienda/Views/Productos/Detalles.cshtml
@model Tienda.Models.Productos

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_price)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Tienda/Tienda/Views/Productos/Editar.cshtml
@model Tienda.Models.Productos

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Productos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               <div class="form-group">
                <label asp-for="Product_id" class="control-label"></label>
                <input asp-for="Product_id" class="form-control" readonly />
                <span asp-validation-for="Product_id" class="text-danger"></span>
            
            <div class="form-group">
                <label asp-for="Product_code" class="control-label"></label>
                <input asp-for="Product_code" class="form-control" />
                <span asp-validation-for="Product_code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_name" class="control-label"></label>
                <input asp-for="Product_name" class="form-control" />
                <span asp-validation-for="Product_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_desc" class="control-label"></label>
                <input asp-for="Product_desc" class="form-control" />
                <span asp-validation-for="Product_desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_price" class="control-label"></label>
                <input asp-for="Product_price" class="form-control" />
                <span asp-validation-for="Product_price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tienda/Tienda/Views/Productos/Eliminar.cshtml
@model Tienda.Models.Productos

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Productos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_price)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Tienda/Tienda/Views/Productos/Index.cshtml
@model IEnumerable<Tienda.Models.Productos>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<form asp-action="Index" method="get">

    <p>
        <i class="fa fa-search"></i>
        <input type="search" name="searchp" placeholder="Ingresa nombre o código del producto" value="@ViewData["GetEmployeesDetails"]" style="width:500px" />
        <input type="submit" name="Buscar" class="btn btn-primary">
        <a asp-action="Index">Ver Todos</a>
    </p>
</form>





<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_desc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product_price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_desc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product_price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Editar", new { id = item.Product_id}, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Detalles", new { id = item.Product_id }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Eliminar", new { id = item.Product_id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Tienda/Tienda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tienda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tienda</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Tienda 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>